Spring branch
ArtikVN/ticket-app pull request #2
Opened 2022-01-19 14:45 UTC by ArtikVN

2022-01-19 15:38 UTC, KseniiaMakarova requested changes

2022-01-19 15:38 UTC, KseniiaMakarova commented on README.md
>  # ticket-app
https://github.com/ArtikVN/ticket-app/blob/a2cdd075fe6a957dba8b840e232dadabd869d831/README.md

it looks like this - let's work a bit on formatting

2022-01-19 15:38 UTC, KseniiaMakarova commented on README.md
> +###Objective of the project:
```suggestion
### Objective of the project:
```
same everywhere

2022-01-19 15:38 UTC, KseniiaMakarova commented on README.md
> +#####Application is ready to go
```suggestion

##### Application is ready to go
```

2022-01-19 15:38 UTC, KseniiaMakarova commented on README.md
> +```GET: /users/by-email``` — find user by email<br>
```suggestion
What requests can an administrator make:

```GET: /users/by-email``` — find user by email<br>
```

2022-01-19 15:38 UTC, KseniiaMakarova commented on README.md
> +```GET: /cinema-halls``` — display all the cinema halls<br>
same

2022-01-19 15:38 UTC, KseniiaMakarova commented on src/main/java/cinema/model/Ticket.java
>      private MovieSession movieSession;
add joinColumn

2022-01-19 15:38 UTC, KseniiaMakarova commented on src/main/java/cinema/model/User.java
>  public class User {
add @Table

2022-01-19 15:38 UTC, KseniiaMakarova commented on src/main/java/cinema/model/User.java
> +            inverseJoinColumns = @JoinColumn(name = "roles"))
fix table and column names

2022-01-19 16:49 UTC, ArtikVN commented on README.md
>  # ticket-app
Странно, в презентации в идее, оно отображалось корректно)

2022-01-20 06:13 UTC, KseniiaMakarova requested changes

2022-01-20 06:13 UTC, KseniiaMakarova commented on src/main/java/cinema/model/Ticket.java
> +import javax.persistence.*;
fix checkstyle

2022-01-20 06:13 UTC, KseniiaMakarova commented on src/main/java/cinema/model/Ticket.java
> +    @ManyToOne(fetch = FetchType.LAZY)
убери LAZY отсюда и из других моделей, если там есть
у тебя сейчас метод get() в AbstractDao, могут быть проблемы

2022-01-20 08:08 UTC, KseniiaMakarova approved these changes

2022-01-20 14:55 UTC, merged